[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "nx-parallel"
authors = [
    {name = "NetworkX Devs", email = "networkx-core@discuss.scientific-python.org"},
]
description = "An experimental parallel backend for NetworkX"
readme = "README.md"
requires-python = ">=3.11"
keywords = ["networkx", "algorithms", "parallel"]
license = {text = "BSD-3-Clause"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "networkx",
    "joblib"
]
version = '0.0.1'

[project.optional-dependencies]
developer = [
    'pre-commit',
    'pytest',
]

[project.entry-points."networkx.plugins"]
parallel = "nx_parallel.interface:Dispatcher"

[tool.setuptools]
py-modules = []

[tool.ruff]
line-length = 88
target-version = 'py311'

[tool.ruff.per-file-ignores]
"__init__.py" = ['I', 'F403']
